config/routes.rb
Rails.application.routes.draw do

  # Redirect root to the sign-in page
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  
  # Update to use the custom controller for registrations
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :links

  get '/l/:slug', to: 'links#redirect_to_large_url', as: 'link_slug'
  post 'l/:slug', to: 'links#redirect_to_large_url_for_private_links', as: 'redirect_to_large_url_for_private_links'


  # Define the route for GET /links/:id_link/report
  get '/links/:id/report', to: 'links#report', as: 'link_report'
  get '/links/:id/report', to: 'links#clear', as: 'link_clear'
  
  # Define root for access denied
  get '/access_denied', to: 'links#access_denied', as: 'access_denied'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/link.rb
require 'securerandom'

class Link < ApplicationRecord
    belongs_to :user
    has_many :visits, dependent: :destroy
    validates :slug, presence: true, uniqueness: true
    validates :large_url, presence: true, format: {
    with: /\A(?:http|https|ftp):\/\/\S+\z/,
    message: "is not a valid URL"
  }

  # perform this action right after calling new and before calling save
  before_validation :complete_information

  # This method generate a unique slug, and assign it to user
  def generate_slug
    loop do
      self.slug = SecureRandom.alphanumeric(6)

      # Check if the generated slug is unique
      break unless Link.exists?(slug: self.slug)
    end
  end

  # checks if the link meets the condition to be displayed, each link type must implement it
  def meets_condition_for_display? (password = nil)
    raise NotImplementedError, "Subclasses must define `meets_condition_for_display?` method."
  end

  # after verifying that the condition for the redirection is met, the visit is created 
  def update_conditions (user_ip_address)
    #creates a visit for the link I want to redirect, with the current date, and the ip address from which the request was made
    Link.find_by(slug: self.slug).visits.create(visited_at: Date.today, ip_address: user_ip_address)
  end

  private

    def complete_information
      if self.slug.nil?
        # Set the slug (automatically generated on the model) to the new link
        generate_slug
      end
    end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_current_user
  before_action :set_and_validate_link_from_id, only: %i[show destroy edit update report clear]
  before_action :set_and_validate_link_from_slug, only: %i[redirect_to_large_url redirect_to_large_url_for_private_links]
  before_action :set_visits_to_link, only: %i[report]
  
  # GET /links or /links.json for @current_user
  def index
    @links = Link.where(user_id: @current_user.id)
  end

  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end
 
  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    # Create the link with form parameters
      # dynamically convert a string into a class name and instantiate an object
    @link = Object.const_get(params[:link_type]).new(link_params)
    
    #The user_id must be obtained from the user who is currently logged in
    @link.assign_attributes(user_id: @current_user.id)  
    
    respond_to do |format|
      if @link.save
        format.html { redirect_to link_url(@link), notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to link_url(@link), notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy!

    respond_to do |format|
      format.html { redirect_to links_url, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # Has the logic to get original link from :slug and redirect to it, 
    #   if meets the conditions depending on the link type
    def redirect_to_large_url
     
        case (@link_to_redirect.type)
        when 'LinkPrivate'
          # redirect to view to request password to user
          render 'private'
        else
          # check if it meets the condition 
          if @link_to_redirect.meets_condition_for_display?
            @link_to_redirect.update_conditions (request.remote_ip) # pass IP address of the client making the request
            redirect_to @link_to_redirect.large_url, allow_other_host: true
          else
            redirection_on_error
          end
        end
    end

    def redirect_to_large_url_for_private_links
      if @link_to_redirect.meets_condition_for_display? (params[:password_private])
        @link_to_redirect.update_conditions(request.remote_ip) # pass IP address of the client making the request
        redirect_to @link_to_redirect.large_url, allow_other_host: true
      else
        flash[:error] = "Error: Invalid password, please try again."
        redirect_to redirect_to_large_url_for_private_links_path
      end
    end
  
  # GET /links/1/report
  # @visits_search include visits for Report #1 (if no filter was applied, return all visits, otherwise, it returns the subset of visits that match the filters)
  # @visits_count include visits for Report #2 (returns a a hash where keys are dates and values are the counts of visits for each day for the specified link)
  def report

    link_id = params[:id]
    ip_address = params[:ip_address]
    start_date = params[:start_date]
    end_date = params[:end_date]

    # @visits_count include visits for Report #2 
    @visits_count = Visit.byLink(link_id).groupByDate

    # @visits_search include visits for Report #1
    if start_date.present? && end_date.present? && start_date > end_date
      flash[:error] = "End Date must be after Start Date"
      redirect_back fallback_location: root_path
    elsif
      @visits_search = Visit.byLink(link_id).byIpAdress(ip_address).byDateRange(start_date, end_date)
    end  
  end

  def clear
    @visits_search = @visits
    render :report
  end

  # To render Access Denied view when User has no access to that link
  def access_denied
  end

   
  private

    def set_current_user
      @current_user = current_user
    end 

    def set_and_validate_link_from_id
      @link = Link.find_by(id: params[:id])
  
      if @link.nil?
        render plain: 'Not Found', status: :not_found
      elsif @link.user_id != @current_user.id
        redirect_to access_denied_path
      end
    end

    def set_and_validate_link_from_slug
      @link_to_redirect = Link.find_by(slug: params[:slug])

      if @link_to_redirect.nil?
        render plain: 'Not Found', status: :not_found
      elsif @link_to_redirect.user_id != @current_user.id
        redirect_to access_denied_path
      end
    end

    def set_visits_to_link
      @visits = @link.visits.all
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.require(:link).permit(:name, :large_url, :slug, :type, :expires_at, :visited, :secret)
    end

    def redirection_on_error
      if @link_to_redirect.type == 'LinkTemporal'
        render plain: 'Not Found', status: :not_found
      elsif @link_to_redirect.type == 'LinkEphemeral'
        render plain: 'Forbidden Access', status: :forbidden
      end
    end

end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_with(model: @link.becomes(Link)) do |form| %>
  <% if link.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <br>

  <div>
    <%= form.label :large_url, style: "display: block" %>
    <%= form.text_field :large_url %>
  </div>

  <br>

  <% if params[:link_type] == "LinkTemporal" || @link.type == "LinkTemporal"%>
    <div>
      <%= form.label :expires_at %>
      <br>
      <%= form.datetime_local_field :expires_at %>
    </div>
  <% end %>

  <br>

  <% if params[:link_type] == "LinkPrivate" || @link.type == "LinkPrivate" %>
    <div>
      <%= form.label :secret %>
      <br>
      <%= form.text_field :secret %>
    </div>
  <% end %>

   <% if @link.type == "LinkEphemeral" %>
    <div>
      <%= form.label :visited %>
      <br>
      <%= form.check_box :visited, checked: @link.visited %>
    </div>
  <% end %>

  <br>

  <!-- include link_type as part of the submit parameters -->
  <% if params[:link_type] %>
    <%= hidden_field_tag :link_type, params[:link_type] %>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/links/_link.html.erb
<div id="<%= dom_id link %>">
  <p>
    <strong>Name:</strong>
    <%= link.name %>
  </p>

  <p>
    <strong>Large url:</strong>
    <%= link.large_url %>
  </p>

  <p>
    <strong>Slug:</strong>
    <%= link.slug %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= link.type %>
  </p>

  <% if link.type == "LinkEphemeral" %>
    <p>
      <strong>Visited:</strong>
      <%= link.visited %>
    </p>
  <% end %>

  <% if link.type == "LinkTemporal" %>
    <p>
      <strong>Expires At:</strong>
      <%= link.expires_at %>
    </p>
  <% end %>





</div>

app/views/links/access_denied.html.erb
<!-- app/views/links/access_denied.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>Access Denied</title>
</head>
<body>
  <h1>Access Denied</h1>
  <p>Sorry, you do not have permission to access this resource.</p>
</body>
</html>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Show this link", link_path(@link) %> |
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/index.html.erb
<%= javascript_include_tag 'application' %>

<p style="color: green"><%= notice %></p>

<style>
    /* Optional: Add styling to the div */
    .right-aligned-div {
      border: 1px solid #ccc;
      padding: 10px;
      margin: 10px;
      float: right;
    }

  hr {
    border: 5px solid #ccc; /* Adjust the color and thickness of the line */
    margin-top: 20px; /* Adjust the top margin */
    margin-bottom: 20px; /* Adjust the bottom margin */
  }
</style>

 <div class="right-aligned-div">
    <p> Welcome <%= @current_user.username %> </p>
    <% if user_signed_in? %>
      <!-- Display logout link if user is signed in -->
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% end %>
  </div>

<h1>Links</h1>

<div id="links">
  
</div>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Type</th>
        <th>Large</th>
        <th>Slug</th>
      </tr>
    </thead>
    <tbody>
      <% @links.each do |link| %>
        <tr>
          <td><%= link.name %></td>
          <td><%= link.type %></td>
          <td><%= link.large_url %></td>
          <td><%= link.slug %></td>
          <td> <%= link_to "Show this link | ", link_path(link) %> </td>
          <td> <%= link_to "Open link | ", link_slug_url(link.slug), target: "_blank" %> </td>
          <td> <%= link_to "See reports", link_report_url(link) %> </td>
        </tr>
       <% end %>
    </tbody>
  </table>

<hr>
<h3> Create New Link </h3>

<%= form_with(url: new_link_path, method: "get") do |form| %>
  <%= form.radio_button(:link_type, "LinkRegular", checked: true) %> Regular
  <%= form.radio_button(:link_type, "LinkPrivate") %> Private
  <%= form.radio_button(:link_type, "LinkEphemeral") %> Ephemeral
  <%= form.radio_button(:link_type, "LinkTemporal") %> Temporal
  <%= form.submit "New Link" %>
<% end %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/private.erb
<h1>Enter Password</h1>

<%= form_with(url: redirect_to_large_url_for_private_links_path, method: :post) do |form| %>
  <%= form.label :password_private %>
  <%= form.text_field :password_private %>

  <%= form.submit 'Submit' %>
<% end %>
<%= link_to "Back to links", links_path %>

app/views/links/private.html.erb
 <div style="color: red">
  <% flash.each do |key, value| %>
    <div class="flash <%= key %>"><%= value %></div>
  <% end %>
</div>

<h1>Enter Password</h1>

<%= form_with(url: redirect_to_large_url_for_private_links_path, method: :post) do |form| %>
  <%= form.label :password_private %>
  <%= form.text_field :password_private %>

  <%= form.submit 'Submit' %>
<% end %>
<%= link_to "Back to links", links_path %>

app/views/links/report.html.erb
<style>
  hr {
    border: 5px solid #ccc; /* Adjust the color and thickness of the line */
    margin-top: 20px; /* Adjust the top margin */
    margin-bottom: 20px; /* Adjust the bottom margin */
  }
</style>

<h1> See reports for link: <%=@link.name%> </h1>
<h3> <b> <%= link_to "Back to links", links_path %> </b></h3>


<h2> <u> Report #1 </u> </h2>
<%= form_with(url: link_report_url, method: "get") do |form| %>
  <%= form.text_field :ip_address, value: params[:ip_address], placeholder: "Search by IP Address" %>
  <!-- Label for start_date -->
  <%= form.label :start_date, "Start Date"%>
  <%= form.date_field :start_date, value: params[:start_date] %>
  <!-- Label for end_date -->
  <%= form.label :end_date, "End Date" %>
  <%= form.date_field :end_date, value: params[:end_date] %>
  <%= form.submit "Search" %>
<% end %>
<p> <b> <%= link_to "Clear", link_clear_url %> </b> </p>

<!-- Display flash messages -->
 <div style="color: red">
  <% flash.each do |key, value| %>
    <div class="flash <%= key %>"><%= value %></div>
  <% end %>
</div>

<p> Amount of results: <%= @visits_search.length %> </p>
<p> <b> Date</b> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | <b> IP address </b> </p>
<% if @visits_search.any? %>
  <% @visits_search.each do |visit| %>
    <p> <%= visit.visited_at.strftime("%m-%d-%Y") %> | <%= visit.ip_address %></p>
  <% end %>
<% else %>
  <p>No results found</p>
<% end %>

<hr>

<h2> <u> Report #2 </u> </h2>

<% if @visits_count.any? %>
  <p> <b> Date</b> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | <b> Amounts of Visits </b> </p>
  <% @visits_count.each do |date, count|%>
    <p> <%= date %> | <%= count %> </p>
  <% end %>
<% else %>
  <p>No results found</p>
<% end %>

app/views/links/show.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to "Back to links", links_path %>
<%= render 'links/link', link: @link %>

<div>
  <%= link_to "Edit this link", edit_link_path(@link) %> |
  <%= link_to "See reports", link_report_url(@link) %> 
  <%= button_to "Destroy this link", link_path(@link), method: :delete %>
</div>